const mongoose = require('mongoose');

// 1. Define Base Options (discriminatorKey tells mongoose to differentiate roles)
const baseOptions = {
  discriminatorKey: 'role', // The field name that differentiates "Student", "Faculty", etc.
  collection: 'users',      // The collection name in MongoDB
  timestamps: true          // Adds createdAt and updatedAt
};

// 2. Define Base Schema (Common fields: id, name, email, password, role)
// Note: 'id' is automatically generated by MongoDB as '_id'. 
// 'role' is automatically managed by the discriminatorKey.
const BaseUserSchema = new mongoose.Schema({
  name: {
    type: String,
    required: [true, 'Name is required'],
    trim: true
  },
  email: {
    type: String,
    required: [true, 'Email is required'],
    unique: true,
    lowercase: true,
    trim: true
  },
  password: {
    type: String,
    required: [true, 'Password is required'],
    minlength: 6
  }
}, baseOptions);

// 3. Create the Base Model
const User = mongoose.model('User', BaseUserSchema);

// 4. Create Discriminators (Specific Roles)

// STUDENT Schema (extends User)
const Student = User.discriminator('Student', new mongoose.Schema({
  enrollmentNo: {
    type: String,
    required: [true, 'Enrollment Number is required'],
    unique: true,
    trim: true
  },
  batchYear: {
    type: String,
    required: [true, 'Batch Year is required']
  },
  degree: {
    type: String,
    required: [true, 'Degree is required'] // e.g., B.Tech, B.Sc
  }
}));

// FACULTY Schema (extends User)
const Faculty = User.discriminator('Faculty', new mongoose.Schema({
  employee_id: {
    type: String,
    required: [true, 'Employee ID is required'],
    unique: true,
    trim: true
  },
  designation: {
    type: String,
    required: [true, 'Designation is required'] // e.g., Professor, HOD
  },
  subjects: {
    type: [String], // Array of subject codes or names
    default: []
  },
  department_name: {
    type: String,
    required: [true, 'Department Name is required']
  }
}));

// ADMIN Schema (extends User)
const Admin = User.discriminator('Admin', new mongoose.Schema({
  adminLevel: {
    type: String, // e.g., "SuperAdmin", "DepartmentAdmin"
    default: 'Standard'
  },
  permissions: {
    type: [String], // e.g., ["manage_users", "edit_courses"]
    default: []
  }
}));

// 5. Export all models
module.exports = {
  User,    // Base model
  Student,
  Faculty,
  Admin
};